import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
// import { MoralisProvider } from 'react-moralis' // MoralisProvider 추가
import { ThemeContextProvider } from '@/context/theme-context' // 테마 컨텍스트
import { ChainContextProvider } from '@/context/chain-context' // 체인 컨텍스트
// import { AuthContextProvider } from "@/context/auth-context"; // 인증 컨텍스트

const geistSans = localFont({
  src: '../../public/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../../public/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//   const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL_MORALIS!
//   const APP_ID = process.env.NEXT_PUBLIC_APP_ID_MORALIS!

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <MoralisProvider serverUrl={SERVER_URL} appId={APP_ID}> */}
        <ThemeContextProvider>
          <ChainContextProvider>
            {/* <AuthContextProvider> */}
            <main>
              {children} {/* 하위 페이지의 콘텐츠 */}
            </main>
            {/* </AuthContextProvider> */}
          </ChainContextProvider>
        </ThemeContextProvider>
        {/* </MoralisProvider> */}
      </body>
    </html>
  )
}
