import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ThemeContextProvider } from '@/context/theme-context' // 테마 컨텍스트
import NavBarWrapper from '@/components/navBarWrapper/navbarWrapper'
import { WagmiContext } from '@/context/wagmi-context'
import { AccountProvider } from '@/context/account-context'
const geistSans = localFont({
  src: '../../public/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../../public/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//   const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL_MORALIS!
//   const APP_ID = process.env.NEXT_PUBLIC_APP_ID_MORALIS!

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <MoralisProvider serverUrl={SERVER_URL} appId={APP_ID}> */}
        <ThemeContextProvider>
          <WagmiContext>
            <AccountProvider>
              <main>
                <NavBarWrapper />
                {children}
              </main>
            </AccountProvider>
          </WagmiContext>
        </ThemeContextProvider>
        {/* </MoralisProvider> */}
      </body>
    </html>
  )
}
